#version: '3.8'
#services:
#  app:
#    image: golf-tournament-management
#    build: ./target
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: hellorobot123
#      MYSQL_DATABASE: Ggolf_DB
#      MYSQL_USER: root
#      MYSQL_PASSWORD: hellorobot123
#    ports:
#      - "3306:3306"

version: '3'
services:
  myapp-main:
    image: golf-tournament-management:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/Ggolf_DB
      #- spring.datasource.url=jdbc:mysql://s4-fall-2022.ce2vcezehro2.us-east-1.rds.amazonaws.com/fall_2022
      - spring.datasource.password=hellorobot123
      - spring.datasource.username=root